### ISSUE TITLE
MessageBoxCenter 组件： 点击后报错

### ISSUE THREAD

**Issue by dream2023** [spaasteam/spaas-ui#23]
![image](https://user-images.githubusercontent.com/19297757/66727032-49e47400-ee6f-11e9-8367-39a8f6dd889e.png)
![image](https://user-images.githubusercontent.com/19297757/66727033-4fda5500-ee6f-11e9-8d6f-28827348c9a8.png)
`$alertCenter` 应该是未全局注册

**Comment by Barretem** [comment]
已经处理详情看：https://github.com/spaasteam/spaas-ui/pull/25
