### ISSUE TITLE
data-mapper支持行或列方式展示及设置labelWidth

### ISSUE THREAD

**Issue by Jack-rainbow** [spaasteam/spaas-ui#26]
**期待的功能**
data-mapper支持行或列方式展示及设置labelWidth 

**OS /浏览器版本**
win10 家庭版（64 位） / chrome  75.0.3770.142（正式版本） （64 位）

**Vue版本**
V2.5.17

**element版本**
V2.12.0

**为什么提出功能需求？** 

- 1.支持行或列方式展示
   希望特定场景满足行及列显示
![image](https://user-images.githubusercontent.com/20368037/67184300-0dd48480-f416-11e9-90fd-6246c56173ef.png)
- 2.设置labelWidth
 
![image](https://user-images.githubusercontent.com/20368037/67204762-d29b7b00-f440-11e9-9f7a-65537bebde88.png)

**目前做法**
`注：css代码未贴出`

- 1.支持行或列方式展示
![image](https://user-images.githubusercontent.com/20368037/67184390-3fe5e680-f416-11e9-9143-27697df0c3ad.png)
- 2.设置labelWidth

![image](https://user-images.githubusercontent.com/20368037/67204871-07a7cd80-f441-11e9-827c-a1006d543e2d.png)

**期望结果**
希望特定场景满足行及列显示及设置labelWidth.

Thank~~

**Comment by Barretem** [comment]
请升级到v2.13.2，已经满足其需求
