### ISSUE TITLE
MessageBoxCenter 图标样式问题

### ISSUE THREAD

**Issue by cjfff** [spaasteam/spaas-ui#38]
**Describe the bug**
全局注册 MessageBoxCenter 后 使用的时候如果加入第三个参数 options 中的 type 的话会造成样式凑五

**To Reproduce**
1. 全局注册 `MessageBoxCenter` 组件 `Vue.prototype.$alert = MessageBoxCenter.alert;`
2. 项目中调用  `this.$alert('测试测试测试。', '提示', { type: 'warning' });`

**Expected behavior**
希望 `type` 的图标在文字的前面而不是居中绝对定位显示

**Screenshots**
![image](https://user-images.githubusercontent.com/20502762/68448539-c70cca00-021e-11ea-900d-01a72404fed8.png)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome
 - Version 78.0.3904.87

**Comment by Barretem** [comment]
已经修复该bug，详情请看：#39

**Comment by Barretem** [comment]
请将版本升级到V2.14.3
